### ISSUE TITLE
RFC - Dynamic metadata value for Location

### ISSUE THREAD

**Issue by iceburg1991** [Wizkunde/SAMLBase#1]
Hello Wizkunde,

Can you make the value of Location within the md:AssertionConsumerService of the metadata template dynamic?

In your Metadata twig template you have a static value for the 'Location' within the md:AssertionConsumerService tag as shown below. My request is to make the Location value, the static url, dynamic like ``` {{ EntityID }} ``` and ``` {{ OrganizationURL }} ```

```xml
<md:AssertionConsumerService isDefault="true" index="0"
    Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    Location="https://sp.example.com/SAML2/SSO/POST"/>
```

Location of metadata twig template: SAMLBase/src/Wizkunde/SAMLBase/Template/Twig/Metadata.xml.twig

**Comment by RonXS** [comment]
Sure thing! Its now dynamic and can be changed with ACSURL!

There are more fixes in the library but i will place that in the documentation
